# Generated by Django 4.2.4 on 2023-08-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("username", models.CharField(max_length=20)),
                ("career", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=20)),
                ("number", models.IntegerField(default=0)),
                ("password", models.CharField(max_length=20)),
                ("location", models.CharField(max_length=20)),
            ],
        ),
    ]
